Repository codesquad-member-2020/baseball-02, pull requests merged in 2020-05, with the labels that each got.

#4 [#3] feat: 공통 gitignore 정의
  .gitignore
Labels: Team, good first issue

#5 [#1] docs: README.md 작성
  README.md
Labels: Team, documentation

#6 [#2] docs: issue template 및 PR template 생성
  .github/ISSUE_TEMPLATE/-be--title.md
  .github/ISSUE_TEMPLATE/-fe--title.md
  .github/ISSUE_TEMPLATE/-ios--title.md
  .github/ISSUE_TEMPLATE/-team--title.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Team, documentation

#10 [#8] feat: Spring Boot 프로젝트 초기화
  BE/baseball/.gitignore
  BE/baseball/build.gradle
  BE/baseball/gradle/wrapper/gradle-wrapper.jar
  BE/baseball/gradle/wrapper/gradle-wrapper.properties
  BE/baseball/gradlew
  BE/baseball/gradlew.bat
  BE/baseball/settings.gradle
  BE/baseball/src/main/java/kr/codesquad/baseball/BaseballApplication.java
  BE/baseball/src/main/resources/application.properties
  BE/baseball/src/test/java/kr/codesquad/baseball/BaseballApplicationTests.java
Labels: Feature

#15 [#12] 서버 설정을 추가합니다.
  BE/baseball/src/main/java/kr/codesquad/baseball/business/controller/dummy
  BE/baseball/src/main/java/kr/codesquad/baseball/business/domain/dummy
  BE/baseball/src/main/java/kr/codesquad/baseball/business/service/dummy
  BE/baseball/src/main/java/kr/codesquad/baseball/common/config/JacksonConfig.java
  BE/baseball/src/main/java/kr/codesquad/baseball/common/config/SpringFoxConfig.java
  BE/baseball/src/main/java/kr/codesquad/baseball/common/config/WebConfig.java
  BE/baseball/src/main/java/kr/codesquad/baseball/common/error/ErrorCode.java
  BE/baseball/src/main/java/kr/codesquad/baseball/common/error/ErrorResponse.java
  BE/baseball/src/main/java/kr/codesquad/baseball/common/error/GlobalRestExceptionHandler.java
  BE/baseball/src/main/java/kr/codesquad/baseball/common/error/exception/BusinessException.java
  BE/baseball/src/main/java/kr/codesquad/baseball/common/error/exception/EntityNotFoundException.java
  BE/baseball/src/main/java/kr/codesquad/baseball/common/error/exception/LoginRequiredException.java
  BE/baseball/src/main/java/kr/codesquad/baseball/common/error/exception/UserNotFoundException.java
  BE/baseball/src/main/java/kr/codesquad/baseball/common/sql/dummy
  BE/baseball/src/main/java/kr/codesquad/baseball/common/util/dummy
Labels: Feature

#16 [#14] 데이터베이스 설정
  BE/baseball/.gitignore
  BE/baseball/build.gradle
  BE/baseball/src/main/resources/application.properties
  BE/baseball/src/main/resources/db/migration/V1.0.0__schema_init.sql
Labels: Feature

#20 [FE] React Router 적용
  FE/package.json
  FE/src/Components/App.jsx
  FE/src/components/Router.jsx
  FE/src/routes/Login.jsx
  FE/src/routes/Match.jsx
  FE/src/routes/PlayerRecord.jsx
  FE/src/routes/TeamChoice.jsx
  FE/src/utils/const.js
  FE/webpack.config.js
Labels: Feature

#25 [#17] 팀 목록 조회 기능 구현
  BE/baseball/src/main/java/kr/codesquad/baseball/business/controller/dummy
  BE/baseball/src/main/java/kr/codesquad/baseball/business/domain/Team.java
  BE/baseball/src/main/java/kr/codesquad/baseball/business/domain/TeamDao.java
  BE/baseball/src/main/java/kr/codesquad/baseball/business/domain/dummy
  BE/baseball/src/main/java/kr/codesquad/baseball/business/service/TeamService.java
  BE/baseball/src/main/java/kr/codesquad/baseball/business/service/dummy
  BE/baseball/src/main/java/kr/codesquad/baseball/web/controller/TeamController.java
  BE/baseball/src/main/java/kr/codesquad/baseball/web/dto/SimpleTeamDto.java
  BE/baseball/src/main/resources/db/migration/V1.0.0__schema_init.sql
  BE/baseball/src/main/resources/db/migration/V1.0.1__team_init.sql
  BE/baseball/src/test/java/kr/codesquad/baseball/web/controller/TeamControllerTest.java
Labels: Feature

#22 [#18] OAuth 기능을 구현했습니다.
  BE/baseball/build.gradle
  BE/baseball/src/main/java/kr/codesquad/baseball/business/domain/user/User.java
  BE/baseball/src/main/java/kr/codesquad/baseball/business/domain/user/UserDAO.java
  BE/baseball/src/main/java/kr/codesquad/baseball/common/config/RestTemplateConfig.java
  BE/baseball/src/main/java/kr/codesquad/baseball/common/config/SpringFoxConfig.java
  BE/baseball/src/main/java/kr/codesquad/baseball/common/config/WebConfig.java
  BE/baseball/src/main/java/kr/codesquad/baseball/common/error/GlobalRestExceptionHandler.java
  BE/baseball/src/main/java/kr/codesquad/baseball/common/oauth/github/GitHubOAuthService.java
  BE/baseball/src/main/java/kr/codesquad/baseball/common/oauth/github/GitHubRequestPayload.java
  BE/baseball/src/main/java/kr/codesquad/baseball/common/oauth/github/GitHubToken.java
  BE/baseball/src/main/java/kr/codesquad/baseball/common/oauth/github/GitHubUser.java
  BE/baseball/src/main/java/kr/codesquad/baseball/common/util/JwtService.java
  BE/baseball/src/main/java/kr/codesquad/baseball/common/util/dummy
  BE/baseball/src/main/java/kr/codesquad/baseball/web/controller/LoginController.java
Labels: Feature

#28 [#23] feat: User Table 설계
  BE/baseball/src/main/resources/db/migration/V1.0.0__schema_init.sql
Labels: Feature

#30 [#29] User 정보를 DB에 저장합니다.
  BE/baseball/src/main/java/kr/codesquad/baseball/business/domain/user/User.java
  BE/baseball/src/main/java/kr/codesquad/baseball/business/domain/user/UserDAO.java
  BE/baseball/src/main/java/kr/codesquad/baseball/business/domain/user/UserDao.java
  BE/baseball/src/main/java/kr/codesquad/baseball/common/error/ErrorCode.java
  BE/baseball/src/main/java/kr/codesquad/baseball/common/error/exception/GitHubUserNotFoundException.java
  BE/baseball/src/main/java/kr/codesquad/baseball/common/oauth/github/GitHubOAuthService.java
  BE/baseball/src/main/java/kr/codesquad/baseball/common/oauth/github/GitHubUser.java
  BE/baseball/src/main/java/kr/codesquad/baseball/common/util/JwtService.java
  BE/baseball/src/main/java/kr/codesquad/baseball/web/controller/LoginController.java
  BE/baseball/src/main/java/kr/codesquad/baseball/web/dto/view/UserView.java
Labels: Feature, enhancement

#32 [FE] 화면 렌더링 구현
  FE/package.json
  FE/src/Components/App.jsx
  FE/src/assets/player.png
  FE/src/components/BallCount.jsx
  FE/src/components/CurrentPlayers.jsx
  FE/src/components/Player.jsx
  FE/src/components/Record.jsx
  FE/src/components/Router.jsx
  FE/src/components/ScoreBoard.jsx
  FE/src/components/Stadium.jsx
  FE/src/index.html
  FE/src/routes/Home.jsx
  FE/src/routes/Login.jsx
  FE/src/routes/Match.jsx
  FE/src/routes/PlayerRecord.jsx
  FE/src/routes/TeamChoice.jsx
  FE/src/styles/App.js
  FE/src/styles/BallCount.js
  FE/src/styles/CurrentPlayers.js
  FE/src/styles/GlobalStyles.js
  FE/src/styles/Home.js
  FE/src/styles/Match.js
  FE/src/styles/Player.js
  FE/src/styles/PlayerRecord.js
  FE/src/styles/Stadium.js
  FE/src/styles/TeamChoice.js
  FE/src/utils/const.js
  FE/webpack.config.js
Labels: Feature
